import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Place from '../../../components/place'
import axios from 'axios'
import { IPlace, DataSets, IDataSet } from '../../../utils/datatypes'
import Head from 'next/head'
import Header from '../../../components/header'
import Footer from '../../../components/footer'
import styles from "styles/Place.module.scss"

export default function PlacePage() {

    const router = useRouter();
    const { id, type } = router.query;
    const [data, setData] = useState<IPlace | undefined>(undefined);
    const [dataSet, setDataSet] = useState<IDataSet | undefined>(undefined);
    useEffect(() => {
        if (!id && !type)
            return;
        fetchData();
    }, [id, type])
    const fetchData = async () => {
        const res = await axios.get('http://localhost:3000/api/place/get', {
            params: {
                objectId: id,
                datasetId: type,
            }
        })

        console.log(res.data);
        setData(res.data);
        DataSets.forEach(function (val) {
            if (val.id == res.data.datasetId) {
                setDataSet(val)
            }
        })
    }
    //console.log(router.query.id)
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700;900&display=swap" rel="stylesheet" />
            </Head>
            <Header />
            <div className='topImage'>


                <h1>{data?.nazev}</h1>
                <img src="/pictures/hrad.jpg" />

            </div>
            {data &&
                <div className={styles.dummy}>
                    {dataSet?.shortName}
                    <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam id dolor. Quisque tincidunt scelerisque libero. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Duis pulvinar. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Vivamus porttitor turpis ac leo. Nullam dapibus fermentum ipsum. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Mauris tincidunt sem sed arcu. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Aenean placerat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed convallis magna eu sem. Mauris elementum mauris vitae tortor.
                    </p>
                    <img src={`http://localhost:3000/api/place/image?objectId=${id}&datasetId=${type}`} />
                </div>
            }
            <Footer/>
        </div>

    )
}
