# Generated by Django 4.1.2 on 2022-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IredoBusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_external_id', models.CharField(blank=True, max_length=30, null=True)),
                ('wkt', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev_okresu', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev', models.CharField(blank=True, max_length=255, null=True)),
                ('kod_vusc', models.CharField(blank=True, max_length=255, null=True)),
                ('oznaceni', models.IntegerField(blank=True, null=True)),
                ('kod_obce', models.IntegerField(blank=True, null=True)),
                ('nazev_orp', models.CharField(blank=True, max_length=255, null=True)),
                ('kod_okresu', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev_obce', models.CharField(blank=True, max_length=255, null=True)),
                ('x', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev_vusc', models.CharField(blank=True, max_length=255, null=True)),
                ('y', models.CharField(blank=True, max_length=255, null=True)),
                ('dp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('kod_orp', models.IntegerField(blank=True, null=True)),
                ('objectid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IredoTrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_external_id', models.CharField(blank=True, max_length=30, null=True)),
                ('wkt', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev_okresu', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev', models.CharField(blank=True, max_length=255, null=True)),
                ('kod_vusc', models.CharField(blank=True, max_length=255, null=True)),
                ('typ', models.CharField(blank=True, max_length=255, null=True)),
                ('oznaceni', models.IntegerField(blank=True, null=True)),
                ('kod_obce', models.IntegerField(blank=True, null=True)),
                ('nazev_orp', models.CharField(blank=True, max_length=255, null=True)),
                ('kod_okresu', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev_obce', models.CharField(blank=True, max_length=255, null=True)),
                ('x', models.CharField(blank=True, max_length=255, null=True)),
                ('nazev_vusc', models.CharField(blank=True, max_length=255, null=True)),
                ('y', models.CharField(blank=True, max_length=255, null=True)),
                ('dp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('kod_orp', models.IntegerField(blank=True, null=True)),
                ('objectid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OredoTransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_external_id', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicletype', models.CharField(blank=True, max_length=255, null=True)),
                ('linenumber', models.IntegerField(blank=True, null=True)),
                ('trainNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('servicenumber', models.IntegerField(blank=True, null=True)),
                ('linetype', models.CharField(blank=True, max_length=255, null=True)),
                ('lon', models.CharField(blank=True, max_length=255, null=True)),
                ('dest', models.CharField(blank=True, max_length=255, null=True)),
                ('dep', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('desttime', models.CharField(blank=True, max_length=255, null=True)),
                ('delay', models.CharField(blank=True, max_length=255, null=True)),
                ('deptime', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('angle', models.IntegerField(blank=True, null=True)),
                ('sourcetype', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_external_id', models.CharField(blank=True, max_length=30, null=True)),
                ('vycka', models.IntegerField(blank=True, null=True)),
                ('zastavka_crz', models.IntegerField(blank=True, null=True)),
                ('z_do', models.CharField(blank=True, max_length=255, null=True)),
                ('typ', models.CharField(blank=True, max_length=255, null=True)),
                ('dopravce_2', models.CharField(blank=True, max_length=255, null=True)),
                ('dopravce_1', models.CharField(blank=True, max_length=255, null=True)),
                ('prijezd_1', models.CharField(blank=True, max_length=255, null=True)),
                ('spoj_2', models.CharField(blank=True, max_length=255, null=True)),
                ('spoj_1', models.IntegerField(blank=True, null=True)),
                ('linka_2', models.CharField(blank=True, max_length=255, null=True)),
                ('cas', models.CharField(blank=True, max_length=255, null=True)),
                ('linka_1', models.CharField(blank=True, max_length=255, null=True)),
                ('tarifni_cislo_1', models.IntegerField(blank=True, null=True)),
                ('odjezd_1', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_1', models.IntegerField(blank=True, null=True)),
                ('ceka_1', models.CharField(blank=True, max_length=255, null=True)),
                ('zastavka_nazev', models.CharField(blank=True, max_length=255, null=True)),
                ('dp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_2', models.CharField(blank=True, max_length=255, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
