# Generated by Django 4.1.2 on 2022-10-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_remove_iredotrainstop_objectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingconnection',
            name='zastavka_crz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
